apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-sjf-meta-pv-3
  namespace: sjf
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-meta-storage
  local:
    path: /kubernetes/garage/s3/meta-3/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ramberget
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-sjf-pv-3
  namespace: sjf
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-data-storage
  local:
    path: /kubernetes/garage/s3/data-3/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ramberget