apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
  namespace: minio-operator
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-local-storage
  local:
    path: /kubernetes/s3/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ramberget